### connection
# curl -i -X POST -d '{"email":"john.doe@les-enovateurs.com","password":"d","token":null}' http://127.0.0.1:8080/api/login
POST http://127.0.0.1:8080/api/login
Content-Type: application/x-www-form-urlencoded

{"email":"john.doe@les-enovateurs.com","password":"azerty","token":null}

###
GET http://127.0.0.1:8080/api/user/courses
Content-Type: application/x-www-form-urlencoded

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE1ODQyOTE3Nzd9.slFwhe5nuISWa_CjXZoGUIGL9Qjq2cfyh4HSj9yARHE"}

###
